### ISSUE TITLE
ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl when creating Invoices

### ISSUE THREAD

**Issue by josh-s-g** [XeroAPI/Xero-Java#219]
- Version 4.1.4

`java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl` is thrown when attempting to create an invoice:

```scala
val defaultClient = new ApiClient()
val accountingApi = AccountingApi.getInstance(defaultClient)
val invoices = new Invoices().addInvoicesItem(...)
accountingApi.createInvoices(token, tenantId, invoices, false, 2)
```
Stack Trace:
```
app java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
app 	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:122)
app 	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
app 	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
app 	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:80)
app 	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:99)
app 	at com.xero.api.client.AccountingApi.createInvoicesForHttpResponse(AccountingApi.java:3702)
app 	at com.xero.api.client.AccountingApi.createInvoices(AccountingApi.java:3648)

```
I'm using the SDK with Scala 2.12.12 and sbt 1.1.1

**Comment by SidneyAllen** [comment]
@josh-s-g 

This sounds very similar to issue 128

See the comment here where the developer identifies the issue and possible solution.  - I hope this helps.
https://github.com/XeroAPI/Xero-Java/issues/128#issuecomment-466161484

**Comment by josh-s-g** [comment]
Thanks for the pointers; manually adding 
```
  "com.sun.jersey" % "jersey-client" % "1.12",
  "com.sun.jersey" % "jersey-core" % "1.12",
```
to my dependencies seems to have done the trick

**Comment by mismaiel62** [comment]
java.lang.NoClassDefFoundError: javax/ws/rs/core/UriBuilder
I am facing this issue. Does anyone know what was the fix?
