### ISSUE TITLE
Getting Deserialization issue once Manual Journal is created through SDK

### ISSUE THREAD

**Issue by ilyassoomro** [XeroAPI/Xero-Java#247]
```
com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "Date": com.xero.models.accounting.ManualJournal#setDate(1 params) vs com.xero.models.accounting.ManualJournal#setDate(1 params)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:269)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25)
    at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669)
    at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
    at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
    at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2803)
    at com.xero.api.client.AccountingApi.createManualJournals(AccountingApi.java:4416)
    at ...
```

Do you think there need `@JsonIgnore` annotation at one of the setter method?

https://github.com/XeroAPI/Xero-Java/blob/56752930ee5ddecefbf776a3eb08bc49947136f7/src/main/java/com/xero/models/accounting/ManualJournal.java#L190

**Comment by SidneyAllen** [comment]
@ilyassoomro - this is the first time I heard of any issue with this property on this object.

Can you provide more information about which version of the SDK you are using and what value you are passing into the setDate method on the ManualJournal Object.

**Comment by ilyassoomro** [comment]
@SidneyAllen - I set manual journal date as following
```
java.util.Date transactionDate = unpostedTransactions.getTransDate();
org.threeten.bp.LocalDate dateThreeTenFormat = Instant.ofEpochMilli(transactionDate.getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
manualJournal.setDate(dateThreeTenFormat); // transaction Date
```

The manual journal is creating at Xero, but while reading its response at following line, I was getting reported exception
```
return apiClient.getObjectMapper().readValue(response.getContent(), typeRef);
```
The `ObjectMapper` is unable to populate `ManualJournal` object from response, due to conflicting `setDate` method in `ManualJournal.java`.

**Comment by SidneyAllen** [comment]
@ilyassoomro - I've tested the following code and it runs successfully.  I had to change the line "unpostedTransactions.getTransDate()" as that method doesn't exist in our codebase.

                java.util.Date transactionDate = new GregorianCalendar(2019, Calendar.FEBRUARY, 11).getTime();
            	org.threeten.bp.LocalDate dateThreeTenFormat = Instant.ofEpochMilli(transactionDate.getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
            	
                // Create Manual Journal
                where = "Type==\"EXPENSE\" && Status ==\"ACTIVE\"";
                Accounts accounts = accountingApi.getAccounts(accessToken, xeroTenantId, ifModifiedSince, where, order);
                String accountCode = accounts.getAccounts().get(0).getCode();
                where = null;
                ManualJournals manualJournals = new ManualJournals();
                // create first MJ
                ManualJournal manualJournal = new ManualJournal();
                manualJournal.setDate(dateThreeTenFormat);
                manualJournal.setNarration("Foo bar");

                ManualJournalLine credit = new ManualJournalLine();
                credit.setDescription("Hello there");
                credit.setAccountCode(accountCode);
                credit.setLineAmount(100.00);
                manualJournal.addJournalLinesItem(credit);

                ManualJournalLine debit = new ManualJournalLine();
                debit.setDescription("Goodbye");
                debit.setAccountCode(accountCode);
                debit.setLineAmount(-100.00);
                manualJournal.addJournalLinesItem(debit);
                manualJournals.addManualJournalsItem(manualJournal);
                System.out.println(manualJournals.toString());


The print statement outputs the newly created ManualJournal object returned from the API.

        class ManualJournals {
            manualJournals: [class ManualJournal {
                narration: Foo bar
                journalLines: [class ManualJournalLine {
                    lineAmount: 100.0
                    accountCode: 101
                    accountID: null
                    description: Hello there
                    taxType: null
                    tracking: []
                    taxAmount: null
                    isBlank: null
                }, class ManualJournalLine {
                    lineAmount: -100.0
                    accountCode: 101
                    accountID: null
                    description: Goodbye
                    taxType: null
                    tracking: []
                    taxAmount: null
                    isBlank: null
                }]
                date: /Date(1549843200000+0000)/
                lineAmountTypes: null
                status: null
                url: null
                showOnCashBasisReports: null
                hasAttachments: false
                updatedDateUTC: null
                manualJournalID: null
                statusAttributeString: null
                warnings: []
                validationErrors: []
                attachments: []
            }]
        }

**Comment by ilyassoomro** [comment]
@SidneyAllen Thank you for looking into the concern. I was wondering why your Test Code `com.xero.api.client.AccountingApiManualJournalsTest.createManualJournalsTest()` working perfectly, but when I was calling `createManualJournals()` It is throwing `JsonMappingException`. May be it is due to conflicting jar or ObjectMapper setting in our project. 
However, I was able to resolve the problem by rebuilding your SDK after adding `@JsonIgnore` annotation over following method in `ManualJournal.java`.
```
  @JsonIgnore
  public void setDate(LocalDate date) {
    // CONVERT LocalDate args into MS DateFromat String
    Instant instant = date.atStartOfDay(ZoneId.of("UTC").normalized()).toInstant();
    long timeInMillis = instant.toEpochMilli();

    this.date = "/Date(" + Long.toString(timeInMillis) + "+0000)/";
  }
```

**Comment by SidneyAllen** [comment]
@ilyassoomro - Not sure what the difference could be.  Often the environment or other dependencies can create anomalies. Sounds like we can close this issue.  All the best!
