### ISSUE TITLE
Creating many bank transactions at once results in time out exception

### ISSUE THREAD

**Issue by max-preuschen** [XeroAPI/Xero-Java#25]
I'm getting a `java.net.SocketTimeoutException: Read timed out` when trying to create a lot of bank transactions at once. 

I think this is because of the standard value for `readTimeout` (20 sec) defined in `com.google.api.client.http.HttpRequest`. There is a method `setReadTimeout` to pass a custom value.
This probably should be called in `com.xero.api.OAuthRequestResource`.`execute()`, where the HttpRequest is being created.

Is there any possibility to set the time-out manually?

```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:918)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:232)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.google.api.client.http.apache.ApacheHttpRequest.execute(ApacheHttpRequest.java:67)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.xero.api.OAuthRequestResource.execute(OAuthRequestResource.java:139)
	at com.xero.api.XeroClient.put(XeroClient.java:171)
	at com.xero.api.XeroClient.createBankTransactions(XeroClient.java:336)
```

**Comment by trungie** [comment]
Probably best done via a Config attribute. 

@max-preuschen How many bank transactions are you creating at once which causes this?

**Comment by max-preuschen** [comment]
In my case I was creating 50-100 bank transactions.
I ended up creating my own HttpRequest, so I am able to set the timeout.

**Comment by trungie** [comment]
@max-preuschen Would this help? https://github.com/trungie/Xero-Java/commit/6b64d5a9c641c2c33fb7278189faa0e34019470b

**Comment by trungie** [comment]
I'll run a few tests too before submitting a PR.

**Comment by SidneyAllen** [comment]
Timeout can [now be set in JsonConfig](
https://github.com/XeroAPI/Xero-Java/commit/afeebd3a68c311d1581805302a2b53ce0e5e83b7)
