### ISSUE TITLE
Get tenant connections

### ISSUE THREAD

**Issue by avinashmadireddy** [XeroAPI/Xero-Java#309]
Hi,

 Trying to get the list of connections as stated in the code. But getting following exception

						ApiClient defaultIdentityClient = new ApiClient("https://api.xero.com", null, null, null, null);
						IdentityApi idApi = new IdentityApi(defaultIdentityClient);
						List<Connection> connection = idApi.getConnections(tokenResponse.getAccessToken(), uuid);

java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:122)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:80)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:99)
	at com.xero.api.client.IdentityApi.getConnectionsForHttpResponse(IdentityApi.java:245)
	at com.xero.api.client.IdentityApi.getConnections(IdentityApi.java:207)
	at 

Version: 4.15.1

**Comment by rdemarco-xero** [comment]
Tested with version 4.15.1 and was unable to reproduce this error
