### ISSUE TITLE
Fetch accounts

### ISSUE THREAD

**Issue by avinashmadireddy** [XeroAPI/Xero-Java#312]
**SDK  (please complete the following information):**
 - Version : 4.15.1

**Describe the bug**

**To Reproduce**

                 ApiClient defaultClient = new ApiClient();
		AccountingApi apiInstance = AccountingApi.getInstance(defaultClient);
		String order = "Name ASC";
		try {
			String accessToken = getAccessToken();
			Accounts accounts = apiInstance.getAccounts(accessToken, xeroTenantId, null, null, order);
			System.out.println(accounts);
		} catch (XeroException e) {
			System.err.println("Exception when calling AccountingApi#getAccounts");
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

**Expected behavior**
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:122)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:80)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:99)
	at

**Comment by rdemarco-xero** [comment]
Tested version 4.15.1 and was unable to reproduce
