### ISSUE TITLE
Update to use jakarta package / Spring Boot 3 compatibility

### ISSUE THREAD

**Issue by awm0999** [XeroAPI/Xero-Java#339]
The current version of Xero-Java does not appear to work with Spring 3, causing runtime errors because of the switch to Jakarta e.g.:

`java.lang.ClassNotFoundException: javax.ws.rs.core.UriBuilder`

Update Xero-Java to replace use of `javax` package with the `jakarta` package?

See:
https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0
https://stackoverflow.com/questions/76119446/strange-issues-with-javax-ws-rs-core-uribuilder

**Comment by rdemarco-xero** [comment]
Hi @awm0999 , could you add this to your pom.xml to see if it resolves the issue?

```
<dependency>
    <groupId>javax.ws.rs</groupId>
    <artifactId>javax.ws.rs-api</artifactId>
    <version>2.0.1</version>
</dependency>
```

**Comment by awm0999** [comment]
Hi @rdemarco-xero and thanks for the prompt reply!

I did try this, but this causes a `ClassCastException`, I'm assuming because of the `javax` / `jakarta` conflict:

```
java.lang.LinkageError: ClassCastException: attempting to castjar:file:/Users/awm0999/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar!/javax/ws/rs/ext/RuntimeDelegate.class to jar:file:/Users/awm0999/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar!/javax/ws/rs/ext/RuntimeDelegate.class
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:146) ~[javax.ws.rs-api-2.0.1.jar:2.0.1]
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120) ~[javax.ws.rs-api-2.0.1.jar:2.0.1]
	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:95) ~[javax.ws.rs-api-2.0.1.jar:2.0.1]
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119) ~[javax.ws.rs-api-2.0.1.jar:2.0.1]
	at com.xero.api.client.IdentityApi.getConnectionsForHttpResponse(IdentityApi.java:246) ~[xero-java-4.27.0.jar:na]
	at com.xero.api.client.IdentityApi.getConnections(IdentityApi.java:208) ~[xero-java-4.27.0.jar:na]
```

Similar experience as posted here:
https://stackoverflow.com/questions/76119446/strange-issues-with-javax-ws-rs-core-uribuilder

I'll revert back to Spring Boot 2.7.11 for now, but would be useful to be able to upgrade to version 3 shortly.
Thanks for taking the time to reply on this though, I appreciate it.

**Comment by rdemarco-xero** [comment]
Awesome, glad to hear! I'll go ahead and close this issue.
