### ISSUE TITLE
StackOverflowError in XeroExceptionHandler

### ISSUE THREAD

**Issue by LeonisX** [XeroAPI/Xero-Java#74]
Today I found the following error in the logs:

```
java.lang.StackOverflowError: null
	at com.xero.api.exception.XeroExceptionHandler.convertException(XeroExceptionHandler.java:93)
	at com.xero.api.exception.XeroExceptionHandler.handleBadRequest(XeroExceptionHandler.java:80)
	at com.xero.api.exception.XeroExceptionHandler.convertException(XeroExceptionHandler.java:94)
	at com.xero.api.exception.XeroExceptionHandler.handleBadRequest(XeroExceptionHandler.java:80)
	at com.xero.api.exception.XeroExceptionHandler.convertException(XeroExceptionHandler.java:94)
	at com.xero.api.exception.XeroExceptionHandler.handleBadRequest(XeroExceptionHandler.java:80)
	at com.xero.api.exception.XeroExceptionHandler.convertException(XeroExceptionHandler.java:94)
	at com.xero.api.exception.XeroExceptionHandler.handleBadRequest(XeroExceptionHandler.java:80)
	at com.xero.api.exception.XeroExceptionHandler.convertException(XeroExceptionHandler.java:94)
	at com.xero.api.exception.XeroExceptionHandler.handleBadRequest(XeroExceptionHandler.java:80)
```

Theoretically, this error should never have occurred, but, nevertheless, it happened.

To reproduce it, it is enough to perform this test:

```
    @Test
    public void handleOtherErrorRequest() throws Exception {
        when(httpResponseException.getContent()).thenReturn("dummy");
        when(httpResponseException.getStatusCode()).thenReturn(400);
        XeroApiException xeroApiException = xeroExceptionHandler.handleBadRequest(httpResponseException);
        assertNotNull(xeroApiException);
        assertNotNull(xeroApiException.getMessages());
        assertNotNull(xeroApiException.getMessage());
    }
```
I prepared a commit with my proposal for its correction: https://github.com/XeroAPI/Xero-Java/pull/73

I hope to see it in the upcoming version of the API

**Comment by SidneyAllen** [comment]
thanks for the PR @LeonisX - merged into version 1.0.0
