### ISSUE TITLE
NPE in ModelBuilder

### ISSUE THREAD

**Issue by bsutton** [XeroAPI/Xero-Java#88]
I'm trying to connect to the zero api with a private application.

When I call new XeroClient I'm getting an NPE in ModelBuilder as below.

My config.json is a copy/paste from the sample code:

````
{
  "AppType" : "PRIVATE",
  "UserAgent": "NNNN",
  "ConsumerKey" : "TTTT",
  "ConsumerSecret" : "YYYYY,
  "PrivateKeyCert" :  "certs/public_privatekey.pfx",
  "PrivateKeyPassword" :  "XXXXX"
}
````

The stack trace is:

````

java.lang.NullPointerException
	at sun.misc.MetaIndex.mayContain(MetaIndex.java:242)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1032)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:292)
	at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1264)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1091)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:232)
	at java.lang.Class.getResourceAsStream(Class.java:2223)
	at com.xero.api.RsaSignerFactory.<init>(RsaSignerFactory.java:21)
	at com.xero.api.ConfigBasedSignerFactory.createSigner(ConfigBasedSignerFactory.java:18)
	at com.xero.api.OAuthRequestResource.createParameters(OAuthRequestResource.java:339)
	at com.xero.api.OAuthRequestResource.execute(OAuthRequestResource.java:211)
	at com.xero.api.XeroClient.get(XeroClient.java:84)
	at com.xero.api.XeroClient.get(XeroClient.java:70)
	at com.xero.api.XeroClient.getContacts(XeroClient.java:539)
	at au.org.noojee.auditor.xero.XeroApi.getContacts(XeroApi.java:41)
	at au.org.noojee.auditor.xero.XeroApiTest.test(XeroApiTest.java:20)

````

**Comment by bsutton** [comment]
OK, found the answer to my problem.
The ModelBuilder NPE was a red herring.

The NPE from the MetaIndex was due the XeroClient not finding my config file and then I believe that it failed to find the private key file (because it then used the default path).

So this is a terrible error for something as simple as not finding the private key file.

The system should put out a meaning full error which includes the path that it tried to load the file from.

Can I also say that using class path resource loaders is ALWAYS a bad idea for config files.
Failures to find the file are always just about impossible to diagnose as it normally gives poor errors (like this one) and then relies on intimate knowledge of how class paths work to correctly locate where the file should live.
Please offer an option to specify an absolute path to the config file or at the very least improve the error messages.

**Comment by bsutton** [comment]
Thanks.
